language: python
sudo: false
os: linux
dist: xenial
matrix:
  include:
  - python: nightly
services:
- docker
addons:
  apt:
    packages:
    - python-commandnotfound
    - python3-commandnotfound
before_install:
- openssl aes-256-cbc -K $encrypted_2a68b6131c57_key -iv $encrypted_2a68b6131c57_iv
  -in root_key.enc -out root_key -d
- if [[ $TRAVIS_OS_NAME == "osx" ]]; then rm -rf /usr/local/include/c++; fi
- if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew update; fi
- if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew unlink python@2; fi
- if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew upgrade python; fi
- if [[ $TRAVIS_OS_NAME == "osx" ]]; then pip3 install virtualenv; fi
- if [[ $TRAVIS_OS_NAME == "osx" ]]; then virtualenv venv -p python3; fi
- if [[ $TRAVIS_OS_NAME == "osx" ]]; then source venv/bin/activate; fi
- pip install -U pip
- pip install -U coveralls
install:
- pip install -Ur requirements.txt
- python setup.py develop
- rm -rf build
before_script:
- bash test_mypy.sh
